# Build on multiple platforms - https://docs.microsoft.com/azure/devops/pipelines/get-started-multiplatform?view=azure-devops&WT.mc_id=devops-github-shboyer
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)
#  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@3
  displayName: Installing .NET Core 3
  inputs:
    packageType: 'sdk'
    version: '3.0.0'

- task: DotNetCoreCLI@3
  displayName: Restoring Packages for Solution
  inputs:
    command: restore
    projects: '**/*.sln'

- task: DotNetCoreCLI@3
  displayName: Build Solution
  inputs:
    command: build
    projects: '**/*.sln'
    arguments: '--no-restore --configuration Release' 

- script: dotnet test source/DasBlog.Tests/UnitTests/ --logger trx;LogfileName=test_results.xml --results-directory $(System.DefaultWorkingDirectory)/test_results --filter Category=UnitTest
  displayName: Run Unit Tests
  condition: and(succeeded(), eq(variables['imageName'], 'windows-2019'))

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: and(always(), eq(variables['imageName'], 'windows-2019'))
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/test_results'

- task: DotNetCoreCLI@3
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'DasBlog-Build-Artifacts'